---
# tasks file for web
- yum_repository:
   name: nexus
   description: nexus repository
   gpgcheck: false
   baseurl: "{{ baseurl }}"
   username: "{{ username }}"
   password: "{{ password }}"

- name: Install my rpm-package
  yum:
   name: sgibnev-app
   state: installed
