---
- name: Ensure that essential packages are installed
  yum:
    pkg: "{{ item }}"
    state: present
  tags:
    - configuration
  loop:
    - epel-release
    - git
    - java-11-openjdk-devel




