pipeline {
  agent any
  stages {
    stage('Install dependencies') {
      steps {
        sh 'npm install'
      }
    }
  stage('Quality check') {
    steps {
      sh 'yarn test'
      }
    }
  stage('Build') {
    steps {
      sh 'yarn build'
      }
    }
  }
}