pipeline {
  agent any
  stages {
    stage('Install dependencies') {
      steps {
        sh 'yarn install'
      }
    }
  stage('Quality check') {
    steps {
      sh 'npx eslint src'
      sh 'yarn run test:nowatch'
      }
    }
  stage('Build') {
    steps {
      sh 'yarn build'
      }
    }
  }
}