---
- name: Install rpm package
  hosts: development

  become: yes

  roles:
    - role: common
      tags: ["configuration"]
    - role: nginx
      tags: ["configuration"]
    - role: web
      tags: ["deployment"]
  environment:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"